### ISSUE TITLE
Difficulty replicating example results.

### ISSUE THREAD

**Issue by awa5114** [usgs/landslides-trigrs#12] opened 2019-10-29 15:37 UTC
I have been trying to replicate the sample results presented in Figure 2-3 of the TRIGRS tutorial manual. DEM, SLOPE, ZMAX, RUNOFF 1 and INFILTRATION 1 are exactly the same. **However, I have problems generating the same maps for RUNOFF 2 and INFILTRATION 2.** I have not yet attempted the maps on rows 4 and 5 of the figure.

Initially I suspected a time step issue, so I tried changing some of the parameters including tx, number of times to save output grids and number of output grids. I also tried rerunning the model with the provided tutorial files in [here](https://pubs.usgs.gov/of/2008/1159/downloads/).  However I had no success.

What could be going wrong here? Thanks in advance.

**Comment by ghost** [comment] 2019-10-29 22:33
I don't think you are doing anything incorrect.  The reason your results don't match is because the rainfall infiltrations used to generate Figure 2-3 are different from those in the sample initialization file.  I'm not sure why the sample file has different values than those used in the tutorial--that was a long time ago.    To get output that matches figure 2-3, intensity (cri(1) for period 1 should be 3.0 x 10-7 m/s and intensity (cri(2) for period 2 should be 3.4x10-6 m/s.   

Other than that, the sample inputs seem to be correct.

**Comment by awa5114** [comment] 2019-10-30 13:50
@baum-usgs thanks for your response. I am now able to reproduce RUNOFF 1, 2 and INFILTRATION 1 and 2. The ranges in the figure are slightly off:

- INFILTRATION 1 --> ranges are 0, 0.3E-6, **0.5184E-6**, 0.7E-6 and1.1E-6
- INFILTRATION 2 --> ranges are 0, 0.4E-5, **0.7003E-5**, 1.3E-5, 1.7E-5
- RUNOFF 1 --> ranges are 0, **2.82E-7**, 4.4E-7, 6E-7 and 8.8E-7
- RUNOFF 2 --> ranges are 0,0.5E-6, **7.2E-6**, 1E-5 and 1.4E-5

Corrected values with respect to Figure 2-3 are shown in **bold**.

 I still can't replicate the images for pressure and factor of safety in rows 4 and 5. In addition to your recommended modification for `cri(2)` I have also modified the following in the tr_in file:

```
Number of times to save output grids
4
Times of output grids 
0.01,43200,86400,100800
```

I assume this is how one can choose to output intermediate time steps. I then tried plotting  `TRp_at_fs_min` files (for times 1 through 4) and `TRfs_min` files (tor times 1 through 4) to replicate images for rows 3 and 4, respectively. However I cannot replicate the plots.

Here's an example of the output array I am getting for `TRfs_min` at time 4 (which I assume is equivalent to 100800 seconds):

```
ncols         10
nrows         10
xllcorner     563435
yllcorner     5258305
cellsize      10
NODATA_value  -9999
2.420 3.609 3.395 2.562 2.420 2.059 2.059 2.059 1.763 1.862
2.420 2.420 1.832 1.730 1.832 1.832 1.763 1.538 1.368 1.340
2.420 1.832 1.730 1.520 1.763 1.368 1.323 1.342 1.342 1.340
1.832 1.763 1.520 1.763 1.368 1.342 1.342 1.323 1.520 1.862
1.763 1.520 1.538 1.342 1.323 1.342 1.340 1.520 1.520 2.440
1.520 1.368 1.323 1.340 1.368 1.340 1.862 2.440 5.119 10.00
1.368 1.340 1.520 1.520 1.763 2.440 5.119 10.00 7.189 2.440
1.520 1.862 2.086 2.440 2.440 10.00 7.189 7.189 2.440 2.086
2.086 2.440 2.440 7.189 10.00 7.189 3.618 2.440 1.763 2.086
3.618 7.189 10.00 10.00 7.189 3.406 2.086 1.763 1.763 1.520
```

You might notice there are no safety factors less than 1 although according to the figure there should be. Any suggestions on how to fix this? Thanks!

**Comment by ghost** [comment] 2019-10-30 23:39
I'm working on this.  I discovered that one part of the problem is that the cohesion values are assigned to the wrong zones in the sample initialization file.  Cohesion in Zone 1 should be 8.0e+03 and cohesion in Zone 2 should be 3.5e+03.  I have confirmed through independent calculations that the program is correctly computing factor of safety.  I'll comment again when I've made more progress.

**Comment by awa5114** [comment] 2019-10-31 08:05
@baum-usgs Switching the zones for the cohesion doesn't really help. Using the same ranges as Figure 2-3, I obtained the following for `TRp_at_fs_min_tutorial_4` (corresponding to t = 100800 s):

<p align="center">
<img src="https://user-images.githubusercontent.com/24267968/67927666-78758500-fbb9-11e9-85d3-0ffb066dbac1.jpeg" width=300>
</p>

Which does not look like the figure in the manual:

<p align="center">
<img src="https://user-images.githubusercontent.com/24267968/67927725-980cad80-fbb9-11e9-994b-81fb77b7e844.JPG" width=200 class="center">
</p>

Although, interestingly enough it looks exactly like the figure for t = 0.01 and t = 43200:

<p align="center">
<img src="https://user-images.githubusercontent.com/24267968/67927786-ca1e0f80-fbb9-11e9-80ed-d5a801846412.JPG" width=200>
</p>

This made me wonder whether the values in `Times of output grids` in Figure 2-3 are incorrect? I then tried running 1 output grid at 216000 s and I got something similar to what is shown for t=100800 seconds in Figure 2-3. For the switched cohesion:

<p align="center">
<img src="https://user-images.githubusercontent.com/24267968/67928945-7c56d680-fbbc-11e9-93bb-0465f5d7ff4c.jpeg" width=300>
</p>

For not switched cohesion:

<p align="center">
<img src="https://user-images.githubusercontent.com/24267968/67929046-af996580-fbbc-11e9-96bf-b85319368ce0.jpeg" width=300>
</p>

Similar, but by no means the same. Look forward to your input. Thanks.

**Comment by awa5114** [comment] 2019-10-31 09:40
An additional remark: on page 66 of the manual, under "Rainfall intensities" the following is stated:

> Thus, period one, which has an intensity of 6E-7 m/s ends after 178200 s and period two begins. After 216000 s, period two, which has an intensity of 2E-5 m/s ends.

This is very different from what we mentioned in the beginning of this thread, namely that 

> To get output that matches figure 2-3, intensity (cri(1) for period 1 should be 3.0 x 10-7 m/s and intensity (cri(2) for period 2 should be 3.4x10-6 m/s.

**Comment by ghost** [comment] 2019-10-31 21:53
After trying various intensities and options unsuccessfully and reviewing the history of revisions of the TRIGRS program and its user guide, I realized (or remembered) that it is not possible to replicate the last two rows in Figure 2-3.  Version 1 of TRIGRS was published in 2002 (see  https://doi.org/10.3133/ofr02424). In 2005 we made revisions  to the program to correct an error in Iverson's (2000) formula for coordinate transformation.  Figure 2-3 in our 2008 user guide was reused from Figure B16 in the user guide for version 1 of TRIGRS published in 2002 (see  https://doi.org/10.3133/ofr02424).  We forgot to update the figure to account for changes to the pore pressure and factor of safety that resulted from this correction.  I had forgotten about that change again until today.  In the original version, upon which Figure 2-3 was based, the hydraulic diffusivity, _D_ was multiplied by the cos^2(_delta_), where _delta_ is the slope angle.  This was based on Equations 24 and 26 in Iverson (2000).  The correction made in 1985 and propagated into the current version of TRIGRS is that _D_ is divided by cos^2(_delta_) (see 2008 user guide, p. 5, line 9).

Reference:
Iverson, R.M., 2000, Landslide triggering by rain infiltration: Water Resources Research, v. 36, no.
7, p. 1,897–1,910.

**Closed as completed** 2021-03-16 22:16 UTC
